// MIREVA seed library — generated by scripts/generate-assets.py. Do not edit by hand.
export const SEED_LIBRARY = [
  {
    "id": "mireva-001",
    "title": "Fern Interval",
    "category": "Nature",
    "tags": [
      "green",
      "botanical",
      "organic"
    ],
    "description": "A generated study in layered greens and low light, built from soft gradient fields.",
    "src": "assets/images/mireva-001.svg",
    "thumb": "assets/thumbnails/mireva-001.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-11-12",
    "source": "generated"
  },
  {
    "id": "mireva-002",
    "title": "Moss & Morning",
    "category": "Nature",
    "tags": [
      "botanical",
      "green",
      "organic"
    ],
    "description": "A generated study in layered greens and low light, built from soft gradient fields.",
    "src": "assets/images/mireva-002.svg",
    "thumb": "assets/thumbnails/mireva-002.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-04-23",
    "source": "generated"
  },
  {
    "id": "mireva-003",
    "title": "Quiet Canopy",
    "category": "Nature",
    "tags": [
      "botanical",
      "earth",
      "organic"
    ],
    "description": "A generated study in layered greens and low light, built from soft gradient fields.",
    "src": "assets/images/mireva-003.svg",
    "thumb": "assets/thumbnails/mireva-003.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-03-07",
    "source": "generated"
  },
  {
    "id": "mireva-004",
    "title": "Verdant Drift",
    "category": "Nature",
    "tags": [
      "calm",
      "botanical",
      "earth"
    ],
    "description": "A generated study in layered greens and low light, built from soft gradient fields.",
    "src": "assets/images/mireva-004.svg",
    "thumb": "assets/thumbnails/mireva-004.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-08-18",
    "source": "generated"
  },
  {
    "id": "mireva-005",
    "title": "Low Tide Reeds",
    "category": "Nature",
    "tags": [
      "earth",
      "calm",
      "organic"
    ],
    "description": "A generated study in layered greens and low light, built from soft gradient fields.",
    "src": "assets/images/mireva-005.svg",
    "thumb": "assets/thumbnails/mireva-005.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-01-02",
    "source": "generated"
  },
  {
    "id": "mireva-006",
    "title": "Understory",
    "category": "Nature",
    "tags": [
      "organic",
      "earth",
      "landscape"
    ],
    "description": "A generated study in layered greens and low light, built from soft gradient fields.",
    "src": "assets/images/mireva-006.svg",
    "thumb": "assets/thumbnails/mireva-006.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-12-13",
    "source": "generated"
  },
  {
    "id": "mireva-007",
    "title": "Concrete Rhythm",
    "category": "Architecture",
    "tags": [
      "form",
      "urban",
      "minimal"
    ],
    "description": "A structural composition of arcs, blocks and negative space in cool concrete tones.",
    "src": "assets/images/mireva-007.svg",
    "thumb": "assets/thumbnails/mireva-007.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-05-24",
    "source": "generated"
  },
  {
    "id": "mireva-008",
    "title": "Brutal Arc",
    "category": "Architecture",
    "tags": [
      "concrete",
      "geometry",
      "structure"
    ],
    "description": "A structural composition of arcs, blocks and negative space in cool concrete tones.",
    "src": "assets/images/mireva-008.svg",
    "thumb": "assets/thumbnails/mireva-008.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-04-08",
    "source": "generated"
  },
  {
    "id": "mireva-009",
    "title": "Stair Study",
    "category": "Architecture",
    "tags": [
      "geometry",
      "form",
      "minimal"
    ],
    "description": "A structural composition of arcs, blocks and negative space in cool concrete tones.",
    "src": "assets/images/mireva-009.svg",
    "thumb": "assets/thumbnails/mireva-009.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-09-19",
    "source": "generated"
  },
  {
    "id": "mireva-010",
    "title": "Facade No. 7",
    "category": "Architecture",
    "tags": [
      "structure",
      "concrete",
      "minimal"
    ],
    "description": "A structural composition of arcs, blocks and negative space in cool concrete tones.",
    "src": "assets/images/mireva-010.svg",
    "thumb": "assets/thumbnails/mireva-010.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-02-03",
    "source": "generated"
  },
  {
    "id": "mireva-011",
    "title": "Column & Void",
    "category": "Architecture",
    "tags": [
      "form",
      "concrete",
      "geometry"
    ],
    "description": "A structural composition of arcs, blocks and negative space in cool concrete tones.",
    "src": "assets/images/mireva-011.svg",
    "thumb": "assets/thumbnails/mireva-011.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-01-14",
    "source": "generated"
  },
  {
    "id": "mireva-012",
    "title": "Atrium Section",
    "category": "Architecture",
    "tags": [
      "form",
      "concrete",
      "minimal"
    ],
    "description": "A structural composition of arcs, blocks and negative space in cool concrete tones.",
    "src": "assets/images/mireva-012.svg",
    "thumb": "assets/thumbnails/mireva-012.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-06-25",
    "source": "generated"
  },
  {
    "id": "mireva-013",
    "title": "Harbour Blue",
    "category": "Travel",
    "tags": [
      "horizon",
      "coast",
      "open"
    ],
    "description": "A horizon study in maritime blues, evoking distance, water and open air.",
    "src": "assets/images/mireva-013.svg",
    "thumb": "assets/thumbnails/mireva-013.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-05-09",
    "source": "generated"
  },
  {
    "id": "mireva-014",
    "title": "Coastal Passage",
    "category": "Travel",
    "tags": [
      "water",
      "horizon",
      "blue"
    ],
    "description": "A horizon study in maritime blues, evoking distance, water and open air.",
    "src": "assets/images/mireva-014.svg",
    "thumb": "assets/thumbnails/mireva-014.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-10-20",
    "source": "generated"
  },
  {
    "id": "mireva-015",
    "title": "Southbound",
    "category": "Travel",
    "tags": [
      "coast",
      "open",
      "horizon"
    ],
    "description": "A horizon study in maritime blues, evoking distance, water and open air.",
    "src": "assets/images/mireva-015.svg",
    "thumb": "assets/thumbnails/mireva-015.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-03-04",
    "source": "generated"
  },
  {
    "id": "mireva-016",
    "title": "Salt Air",
    "category": "Travel",
    "tags": [
      "horizon",
      "coast",
      "open"
    ],
    "description": "A horizon study in maritime blues, evoking distance, water and open air.",
    "src": "assets/images/mireva-016.svg",
    "thumb": "assets/thumbnails/mireva-016.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-02-15",
    "source": "generated"
  },
  {
    "id": "mireva-017",
    "title": "Ferry Window",
    "category": "Travel",
    "tags": [
      "coast",
      "blue",
      "open"
    ],
    "description": "A horizon study in maritime blues, evoking distance, water and open air.",
    "src": "assets/images/mireva-017.svg",
    "thumb": "assets/thumbnails/mireva-017.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-07-26",
    "source": "generated"
  },
  {
    "id": "mireva-018",
    "title": "Peninsula",
    "category": "Travel",
    "tags": [
      "horizon",
      "coast",
      "water"
    ],
    "description": "A horizon study in maritime blues, evoking distance, water and open air.",
    "src": "assets/images/mireva-018.svg",
    "thumb": "assets/thumbnails/mireva-018.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2026-06-10",
    "source": "generated"
  },
  {
    "id": "mireva-019",
    "title": "Grain Study I",
    "category": "Photography",
    "tags": [
      "light",
      "contrast",
      "analog"
    ],
    "description": "A monochrome light study exploring grain, falloff and tonal separation.",
    "src": "assets/images/mireva-019.svg",
    "thumb": "assets/thumbnails/mireva-019.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-11-21",
    "source": "generated"
  },
  {
    "id": "mireva-020",
    "title": "Available Light",
    "category": "Photography",
    "tags": [
      "analog",
      "grain",
      "contrast"
    ],
    "description": "A monochrome light study exploring grain, falloff and tonal separation.",
    "src": "assets/images/mireva-020.svg",
    "thumb": "assets/thumbnails/mireva-020.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-04-05",
    "source": "generated"
  },
  {
    "id": "mireva-021",
    "title": "Shutter Half",
    "category": "Photography",
    "tags": [
      "grain",
      "light",
      "analog"
    ],
    "description": "A monochrome light study exploring grain, falloff and tonal separation.",
    "src": "assets/images/mireva-021.svg",
    "thumb": "assets/thumbnails/mireva-021.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-03-16",
    "source": "generated"
  },
  {
    "id": "mireva-022",
    "title": "Silver Print",
    "category": "Photography",
    "tags": [
      "study",
      "monochrome",
      "contrast"
    ],
    "description": "A monochrome light study exploring grain, falloff and tonal separation.",
    "src": "assets/images/mireva-022.svg",
    "thumb": "assets/thumbnails/mireva-022.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-08-27",
    "source": "generated"
  },
  {
    "id": "mireva-023",
    "title": "Contact Sheet",
    "category": "Photography",
    "tags": [
      "study",
      "analog",
      "monochrome"
    ],
    "description": "A monochrome light study exploring grain, falloff and tonal separation.",
    "src": "assets/images/mireva-023.svg",
    "thumb": "assets/thumbnails/mireva-023.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-01-11",
    "source": "generated"
  },
  {
    "id": "mireva-024",
    "title": "Push Two Stops",
    "category": "Photography",
    "tags": [
      "study",
      "contrast",
      "monochrome"
    ],
    "description": "A monochrome light study exploring grain, falloff and tonal separation.",
    "src": "assets/images/mireva-024.svg",
    "thumb": "assets/thumbnails/mireva-024.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-12-22",
    "source": "generated"
  },
  {
    "id": "mireva-025",
    "title": "Berry Composition",
    "category": "Art",
    "tags": [
      "colour",
      "gesture",
      "expressive"
    ],
    "description": "A painterly field of berry and rose pigment layered into a single chroma study.",
    "src": "assets/images/mireva-025.svg",
    "thumb": "assets/thumbnails/mireva-025.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-05-06",
    "source": "generated"
  },
  {
    "id": "mireva-026",
    "title": "Pigment Field",
    "category": "Art",
    "tags": [
      "canvas",
      "pigment",
      "painterly"
    ],
    "description": "A painterly field of berry and rose pigment layered into a single chroma study.",
    "src": "assets/images/mireva-026.svg",
    "thumb": "assets/thumbnails/mireva-026.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-04-17",
    "source": "generated"
  },
  {
    "id": "mireva-027",
    "title": "Gesture No. 3",
    "category": "Art",
    "tags": [
      "gesture",
      "canvas",
      "expressive"
    ],
    "description": "A painterly field of berry and rose pigment layered into a single chroma study.",
    "src": "assets/images/mireva-027.svg",
    "thumb": "assets/thumbnails/mireva-027.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-09-01",
    "source": "generated"
  },
  {
    "id": "mireva-028",
    "title": "Ink & Rose",
    "category": "Art",
    "tags": [
      "pigment",
      "expressive",
      "colour"
    ],
    "description": "A painterly field of berry and rose pigment layered into a single chroma study.",
    "src": "assets/images/mireva-028.svg",
    "thumb": "assets/thumbnails/mireva-028.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-02-12",
    "source": "generated"
  },
  {
    "id": "mireva-029",
    "title": "Chroma Study",
    "category": "Art",
    "tags": [
      "pigment",
      "expressive",
      "canvas"
    ],
    "description": "A painterly field of berry and rose pigment layered into a single chroma study.",
    "src": "assets/images/mireva-029.svg",
    "thumb": "assets/thumbnails/mireva-029.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-01-23",
    "source": "generated"
  },
  {
    "id": "mireva-030",
    "title": "Still Motion",
    "category": "Art",
    "tags": [
      "painterly",
      "gesture",
      "colour"
    ],
    "description": "A painterly field of berry and rose pigment layered into a single chroma study.",
    "src": "assets/images/mireva-030.svg",
    "thumb": "assets/thumbnails/mireva-030.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-06-07",
    "source": "generated"
  },
  {
    "id": "mireva-031",
    "title": "Silk Fold",
    "category": "Fashion",
    "tags": [
      "textile",
      "atelier",
      "drape"
    ],
    "description": "A textile study of folded, draping forms in muted blush and charcoal.",
    "src": "assets/images/mireva-031.svg",
    "thumb": "assets/thumbnails/mireva-031.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-05-18",
    "source": "generated"
  },
  {
    "id": "mireva-032",
    "title": "Blush Drape",
    "category": "Fashion",
    "tags": [
      "textile",
      "drape",
      "soft"
    ],
    "description": "A textile study of folded, draping forms in muted blush and charcoal.",
    "src": "assets/images/mireva-032.svg",
    "thumb": "assets/thumbnails/mireva-032.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-10-02",
    "source": "generated"
  },
  {
    "id": "mireva-033",
    "title": "Atelier Study",
    "category": "Fashion",
    "tags": [
      "soft",
      "atelier",
      "editorial"
    ],
    "description": "A textile study of folded, draping forms in muted blush and charcoal.",
    "src": "assets/images/mireva-033.svg",
    "thumb": "assets/thumbnails/mireva-033.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-03-13",
    "source": "generated"
  },
  {
    "id": "mireva-034",
    "title": "Hem Line",
    "category": "Fashion",
    "tags": [
      "textile",
      "soft",
      "drape"
    ],
    "description": "A textile study of folded, draping forms in muted blush and charcoal.",
    "src": "assets/images/mireva-034.svg",
    "thumb": "assets/thumbnails/mireva-034.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-02-24",
    "source": "generated"
  },
  {
    "id": "mireva-035",
    "title": "Runway Blur",
    "category": "Fashion",
    "tags": [
      "atelier",
      "blush",
      "drape"
    ],
    "description": "A textile study of folded, draping forms in muted blush and charcoal.",
    "src": "assets/images/mireva-035.svg",
    "thumb": "assets/thumbnails/mireva-035.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-07-08",
    "source": "generated"
  },
  {
    "id": "mireva-036",
    "title": "Cashmere Note",
    "category": "Fashion",
    "tags": [
      "editorial",
      "atelier",
      "soft"
    ],
    "description": "A textile study of folded, draping forms in muted blush and charcoal.",
    "src": "assets/images/mireva-036.svg",
    "thumb": "assets/thumbnails/mireva-036.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2026-06-19",
    "source": "generated"
  },
  {
    "id": "mireva-037",
    "title": "Signal Grid",
    "category": "Technology",
    "tags": [
      "digital",
      "systems",
      "precision"
    ],
    "description": "A modular grid composition in cobalt and slate, referencing systems and interfaces.",
    "src": "assets/images/mireva-037.svg",
    "thumb": "assets/thumbnails/mireva-037.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-11-03",
    "source": "generated"
  },
  {
    "id": "mireva-038",
    "title": "Cold Circuit",
    "category": "Technology",
    "tags": [
      "precision",
      "systems",
      "cobalt"
    ],
    "description": "A modular grid composition in cobalt and slate, referencing systems and interfaces.",
    "src": "assets/images/mireva-038.svg",
    "thumb": "assets/thumbnails/mireva-038.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-04-14",
    "source": "generated"
  },
  {
    "id": "mireva-039",
    "title": "Data Terrace",
    "category": "Technology",
    "tags": [
      "precision",
      "network",
      "grid"
    ],
    "description": "A modular grid composition in cobalt and slate, referencing systems and interfaces.",
    "src": "assets/images/mireva-039.svg",
    "thumb": "assets/thumbnails/mireva-039.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-03-25",
    "source": "generated"
  },
  {
    "id": "mireva-040",
    "title": "Blueprint Blue",
    "category": "Technology",
    "tags": [
      "precision",
      "cobalt",
      "network"
    ],
    "description": "A modular grid composition in cobalt and slate, referencing systems and interfaces.",
    "src": "assets/images/mireva-040.svg",
    "thumb": "assets/thumbnails/mireva-040.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-08-09",
    "source": "generated"
  },
  {
    "id": "mireva-041",
    "title": "Node Map",
    "category": "Technology",
    "tags": [
      "digital",
      "grid",
      "network"
    ],
    "description": "A modular grid composition in cobalt and slate, referencing systems and interfaces.",
    "src": "assets/images/mireva-041.svg",
    "thumb": "assets/thumbnails/mireva-041.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-01-20",
    "source": "generated"
  },
  {
    "id": "mireva-042",
    "title": "Interface Study",
    "category": "Technology",
    "tags": [
      "cobalt",
      "network",
      "systems"
    ],
    "description": "A modular grid composition in cobalt and slate, referencing systems and interfaces.",
    "src": "assets/images/mireva-042.svg",
    "thumb": "assets/thumbnails/mireva-042.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-12-04",
    "source": "generated"
  },
  {
    "id": "mireva-043",
    "title": "Coral Bloom",
    "category": "Abstract",
    "tags": [
      "motion",
      "bloom",
      "coral"
    ],
    "description": "A warm gradient field in coral, peach and plum \u2014 MIREVA's signature palette.",
    "src": "assets/images/mireva-043.svg",
    "thumb": "assets/thumbnails/mireva-043.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-05-15",
    "source": "generated"
  },
  {
    "id": "mireva-044",
    "title": "Warm Fracture",
    "category": "Abstract",
    "tags": [
      "motion",
      "field",
      "warm"
    ],
    "description": "A warm gradient field in coral, peach and plum \u2014 MIREVA's signature palette.",
    "src": "assets/images/mireva-044.svg",
    "thumb": "assets/thumbnails/mireva-044.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-04-26",
    "source": "generated"
  },
  {
    "id": "mireva-045",
    "title": "Ember Field",
    "category": "Abstract",
    "tags": [
      "motion",
      "coral",
      "bloom"
    ],
    "description": "A warm gradient field in coral, peach and plum \u2014 MIREVA's signature palette.",
    "src": "assets/images/mireva-045.svg",
    "thumb": "assets/thumbnails/mireva-045.svg",
    "width": 1200,
    "height": 1200,
    "orientation": "square",
    "type": "image/svg+xml",
    "dateAdded": "2025-09-10",
    "source": "generated"
  },
  {
    "id": "mireva-046",
    "title": "Sand & Flame",
    "category": "Abstract",
    "tags": [
      "motion",
      "coral",
      "field"
    ],
    "description": "A warm gradient field in coral, peach and plum \u2014 MIREVA's signature palette.",
    "src": "assets/images/mireva-046.svg",
    "thumb": "assets/thumbnails/mireva-046.svg",
    "width": 1000,
    "height": 1500,
    "orientation": "portrait",
    "type": "image/svg+xml",
    "dateAdded": "2025-02-21",
    "source": "generated"
  },
  {
    "id": "mireva-047",
    "title": "Soft Collision",
    "category": "Abstract",
    "tags": [
      "motion",
      "bloom",
      "warm"
    ],
    "description": "A warm gradient field in coral, peach and plum \u2014 MIREVA's signature palette.",
    "src": "assets/images/mireva-047.svg",
    "thumb": "assets/thumbnails/mireva-047.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2026-01-05",
    "source": "generated"
  },
  {
    "id": "mireva-048",
    "title": "Amber Motion",
    "category": "Abstract",
    "tags": [
      "field",
      "gradient",
      "coral"
    ],
    "description": "A warm gradient field in coral, peach and plum \u2014 MIREVA's signature palette.",
    "src": "assets/images/mireva-048.svg",
    "thumb": "assets/thumbnails/mireva-048.svg",
    "width": 1600,
    "height": 1067,
    "orientation": "landscape",
    "type": "image/svg+xml",
    "dateAdded": "2025-06-16",
    "source": "generated"
  }
];

export const CATEGORIES = ["All", "Nature", "Architecture", "Travel", "Photography", "Art", "Fashion", "Technology", "Abstract"];
